#!/usr/bin/env node
/*
Copyright 2019 Adobe. All rights reserved.
This file is licensed to you under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License. You may obtain a copy
of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under
the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
OF ANY KIND, either express or implied. See the License for the specific language
governing permissions and limitations under the License.
*/

const BaseScript = require('../lib/abstract-script')
const utils = require('../lib/utils')

const fs = require('fs-extra')

// This should eventually be fully covered by `aio runtime deploy`
class UndeployActions extends BaseScript {
  async run () {
    const taskName = 'Undeploy actions'
    this.emit('start', taskName)

    const distManifest = this.config.manifest.dist
    if (!(await fs.exists(distManifest)) || !(await fs.statSync(distManifest)).isFile()) {
      throw new Error(`Cannot undeploy actions, missing ${this._relApp(distManifest)} file (autogenerated on deploy).`)
    }

    await utils.spawnAioRuntimeDeploy(distManifest, 'undeploy')

    // rm autogen manifest
    await fs.unlink(distManifest)

    Object.keys(this.config.actions.urls).forEach(an => {
      this.emit('progress', `/${this.config.ow.namespace}/${this.config.ow.package}/${an}`)
    })

    this.emit('end', taskName)
  }
}

module.exports = UndeployActions
